nvidia = 1
num_val = 8

# model
net = "vit_l_16"
weights = "IMAGENET1K_V1"
# weights = "DEFAULT"

# train_params
transfer = false
lr = 0.001
momentum = 0.9
num_epochs = 25
batch_size = 10

# dataset
which_data = "dataset1"
train_data = "train"
test_data = "test"




